# Generated by Django 3.0.5 on 2020-04-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUbntall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udprml0', models.IntegerField(verbose_name='Уровень приёма(0) лакального РРС')),
                ('udprml1', models.IntegerField(verbose_name='Уровень приёма(1) лакального РРС')),
                ('udprmr0', models.IntegerField(verbose_name='Уровень приёма(0) удалённого РРС')),
                ('udprmr1', models.IntegerField(verbose_name='Уровень приёма(1) удалённого РРС')),
                ('udspeedl', models.FloatField(verbose_name='Емкость приёма локального РРС')),
                ('udspeedr', models.FloatField(verbose_name='Емкость приёма удалённого РРС')),
                ('udnagrl', models.FloatField(verbose_name='Трафик приема локального РРС')),
                ('udnagrr', models.FloatField(verbose_name='Трафик приема удалённого РРС')),
                ('ipubnttwo', models.CharField(max_length=50)),
                ('timewrite', models.DateTimeField(auto_now_add=True, verbose_name='Записано')),
            ],
            options={
                'verbose_name': 'Уровень приёма лакального РРС',
                'verbose_name_plural': 'Уровень приёма лакального РРС',
                'ordering': ['-timewrite'],
            },
        ),
        migrations.CreateModel(
            name='UbntModelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipubntone', models.CharField(max_length=50, verbose_name='IP адрес РРС')),
                ('nameubnt', models.CharField(max_length=50, verbose_name='Имя РРС')),
                ('nameubntline', models.CharField(max_length=100, verbose_name='Название РРЛ')),
                ('statonoff', models.BooleanField()),
                ('ipubntremote', models.CharField(max_length=50, verbose_name='IP адрес РРС (remote)')),
                ('nameubntremote', models.CharField(max_length=50, verbose_name='Имя РРС (remote)')),
            ],
            options={
                'verbose_name': 'IP адрес РРС',
                'verbose_name_plural': 'IP адреса РРС',
            },
        ),
    ]
