# Generated by Django 3.0.5 on 2020-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startproc', models.BooleanField(default=False, verbose_name='Старт/Стоп Selenium')),
            ],
            options={
                'verbose_name': 'Старт/Стоп Selenium',
                'verbose_name_plural': 'Старт/Стоп Selenium',
            },
        ),
    ]
