# Generated by Django 3.0.5 on 2020-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0002_startprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataubntall',
            name='ipubnttworem',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
