# Generated by Django 3.0.5 on 2020-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0003_dataubntall_ipubnttworem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubntmodeltest',
            name='prm_level',
            field=models.IntegerField(default=-90, verbose_name='Минимальный уровень приёма РРС'),
        ),
    ]
