# Generated by Django 3.0.5 on 2020-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0004_ubntmodeltest_prm_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataubntall',
            name='udnagrl_mk',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='udnagrr_mk',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
