# Generated by Django 3.0.5 on 2020-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0005_auto_20200420_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubntmodeltest',
            name='current_list_ip',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
