# Generated by Django 3.0.5 on 2020-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0007_auto_20200427_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubntmodeltest',
            name='prm_level_for_stat',
            field=models.IntegerField(default=-90, verbose_name='Минимальный уровень приёма РРС (Статистика)'),
        ),
    ]
