# Generated by Django 3.0.5 on 2020-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0008_ubntmodeltest_prm_level_for_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_one', models.CharField(max_length=50, verbose_name='Первый IP')),
                ('number_two', models.CharField(max_length=50, verbose_name='Второй IP')),
                ('number_three', models.CharField(max_length=50, verbose_name='Третий IP')),
                ('number_four', models.CharField(max_length=50, verbose_name='Четвёртый IP')),
                ('number_five', models.CharField(max_length=50, verbose_name='Пятый IP')),
                ('number_six', models.CharField(max_length=50, verbose_name='Шестой IP')),
                ('number_seven', models.CharField(max_length=50, verbose_name='Седьмой IP')),
                ('number_eight', models.CharField(max_length=50, verbose_name='Восьмой IP')),
                ('number_nine', models.CharField(max_length=50, verbose_name='Девятый IP')),
                ('number_ten', models.CharField(max_length=50, verbose_name='Десятый IP')),
                ('number_eleven', models.CharField(max_length=50, verbose_name='Одиннадцатый IP')),
                ('number_twelve', models.CharField(max_length=50, verbose_name='Двенадцатый IP')),
                ('number_thirteen', models.CharField(max_length=50, verbose_name='Тринадцатый IP')),
                ('number_fourteen', models.CharField(max_length=50, verbose_name='Четырнадцатый IP')),
                ('number_fifteen', models.CharField(max_length=50, verbose_name='Пятнадцатый IP')),
                ('number_sixteen', models.CharField(max_length=50, verbose_name='Шестнадцатый IP')),
            ],
        ),
        migrations.AlterField(
            model_name='ubntmodeltest',
            name='statonoff',
            field=models.BooleanField(verbose_name='Включение/Выключение мониторинга РРЛ'),
        ),
    ]
