# Generated by Django 3.0.5 on 2020-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0009_auto_20200508_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listurl',
            name='number_eight',
            field=models.CharField(default='', max_length=50, verbose_name='Восьмой IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_eleven',
            field=models.CharField(default='', max_length=50, verbose_name='Одиннадцатый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_fifteen',
            field=models.CharField(default='', max_length=50, verbose_name='Пятнадцатый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_five',
            field=models.CharField(default='', max_length=50, verbose_name='Пятый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_four',
            field=models.CharField(default='', max_length=50, verbose_name='Четвёртый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_fourteen',
            field=models.CharField(default='', max_length=50, verbose_name='Четырнадцатый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_nine',
            field=models.CharField(default='', max_length=50, verbose_name='Девятый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_one',
            field=models.CharField(default='', max_length=50, verbose_name='Первый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_seven',
            field=models.CharField(default='', max_length=50, verbose_name='Седьмой IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_six',
            field=models.CharField(default='', max_length=50, verbose_name='Шестой IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_sixteen',
            field=models.CharField(default='', max_length=50, verbose_name='Шестнадцатый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_ten',
            field=models.CharField(default='', max_length=50, verbose_name='Десятый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_thirteen',
            field=models.CharField(default='', max_length=50, verbose_name='Тринадцатый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_three',
            field=models.CharField(default='', max_length=50, verbose_name='Третий IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_twelve',
            field=models.CharField(default='', max_length=50, verbose_name='Двенадцатый IP'),
        ),
        migrations.AlterField(
            model_name='listurl',
            name='number_two',
            field=models.CharField(default='', max_length=50, verbose_name='Второй IP'),
        ),
    ]
