# Generated by Django 3.0.5 on 2020-07-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0010_auto_20200510_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listurl',
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='mistake_ip',
            field=models.CharField(default='Ok', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udnagrl',
            field=models.FloatField(default=0.0, verbose_name='Трафик приема локального РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udnagrr',
            field=models.FloatField(default=0.0, verbose_name='Трафик приема удалённого РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udprml0',
            field=models.IntegerField(default=-99, verbose_name='Уровень приёма(0) лакального РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udprml1',
            field=models.IntegerField(default=-99, verbose_name='Уровень приёма(1) лакального РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udprmr0',
            field=models.IntegerField(default=-99, verbose_name='Уровень приёма(0) удалённого РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udprmr1',
            field=models.IntegerField(default=-99, verbose_name='Уровень приёма(1) удалённого РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udspeedl',
            field=models.FloatField(default=0.0, verbose_name='Емкость приёма локального РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udspeedr',
            field=models.FloatField(default=0.0, verbose_name='Емкость приёма удалённого РРС'),
        ),
    ]
