# Generated by Django 3.0.5 on 2020-07-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0012_auto_20200705_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataubntall',
            name='ipubnttwo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='ipubnttworem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='mistake_ip',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udnagrl_mk',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udnagrr_mk',
            field=models.CharField(max_length=50),
        ),
    ]
