# Generated by Django 3.0.5 on 2020-07-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0014_auto_20200705_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataubntall',
            name='mistake_ip',
        ),
    ]
