# Generated by Django 3.0.6 on 2020-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0015_remove_dataubntall_mistake_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataubntall',
            name='mistake_ip',
            field=models.CharField(default='Ok', max_length=1000),
            preserve_default=False,
        ),
    ]
