# Generated by Django 3.0.5 on 2020-07-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0016_dataubntall_mistake_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataubntall',
            name='detail_txt',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
