# Generated by Django 3.0.5 on 2020-07-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0017_dataubntall_detail_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubntmodeltest',
            name='distributed_system_onoff',
            field=models.BooleanField(default=False, verbose_name='Если "1" - IP-адрес взят в мониторинг распределённой системой'),
        ),
    ]
