# Generated by Django 3.0.5 on 2020-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0018_ubntmodeltest_distributed_system_onoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataubntall',
            name='textstyleloc0',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='textstyleloc1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='textstylerem0',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='textstylerem1',
            field=models.CharField(default='style', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubntmodeltest',
            name='distributed_system_onoff',
            field=models.BooleanField(default=False, verbose_name='Если "v" - IP-адрес взят в мониторинг распределённой системой (Не заполнять!!! Поле только для чтения)'),
        ),
    ]
