# Generated by Django 3.0.5 on 2020-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0019_auto_20201026_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataubntall',
            name='textstyleloc0',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='textstyleloc1',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='textstylerem0',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='textstylerem1',
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='sl0',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='sl1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='sr0',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataubntall',
            name='sr1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
