# Generated by Django 3.0.5 on 2020-10-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0020_auto_20201026_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataubntall',
            options={'ordering': ['-timewrite'], 'verbose_name': 'Уровень приёма локального РРС', 'verbose_name_plural': 'Уровень приёма локального РРС'},
        ),
        migrations.AddField(
            model_name='ubntmodeltest',
            name='numberubntline',
            field=models.CharField(default='ЦР-00', max_length=50, verbose_name='Номер РРЛ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udprml0',
            field=models.IntegerField(verbose_name='Уровень приёма(0) локального РРС'),
        ),
        migrations.AlterField(
            model_name='dataubntall',
            name='udprml1',
            field=models.IntegerField(verbose_name='Уровень приёма(1) локального РРС'),
        ),
    ]
