# Generated by Django 3.1.3 on 2020-12-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0021_auto_20201029_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataubntall',
            name='sl0',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='sl1',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='sr0',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='sr1',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrl',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrl_mk',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrr',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrr_mk',
        ),
    ]
