# Generated by Django 3.1.3 on 2020-12-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0023_auto_20201211_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrl',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrl_mk',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrr',
        ),
        migrations.RemoveField(
            model_name='dataubntall',
            name='udnagrr_mk',
        ),
    ]
