# Generated by Django 3.1.3 on 2021-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubajax', '0024_auto_20201211_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRestart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schetchik', models.IntegerField(default=0)),
                ('firstid', models.IntegerField()),
            ],
        ),
    ]
